### ISSUE TITLE
The plugin stopped working recently

### ISSUE THREAD

**Issue by vanthoainguyen** [cschleiden/azure-devops-pr-templates#10]
Hi,

We used to the plugin with Azure DevOps and it's been great for few months.
We suspected some recent changes from Azure that broke the plugin. After choosing the template and hit apply, nothing happens, the template is not applied.

**Comment by nschonni** [comment]
Probably from #9, but this functionality exists already if you on Azure DevOps https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=vsts

**Comment by agustins** [comment]
Same in on-premise(TFS) version 16.131.28106.2

**Comment by amandatom** [comment]
On TFS 2017 Update 3.1. The latest version installed fine and created templates, but would not apply them when selected. I installed version 1.0.0.0 and it worked.
